on:
  push:
    branches:
      - personal/ali-arsalan

name: Create Alpha Release

jobs:
  build:
    name: Create Alpha Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
      - name: Get Commit Message
        run: |
          msg=""
          for i in $(git log --format=%h ${{ github.event.before }}..${{ github.event.after }})
          do
            msg+="&#8226; [$(git log --format=%B -n 1 $i)](https://github.com/${{ github.repository }}/commit/$i)<br/>"
          done
          echo ::set-env name=COMMIT_MESSAGE::"$msg"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create Alpha Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-alpha
          release_name: V${{ steps.package-version.outputs.current-version}}-alpha
          body: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: false
