on:
  push:
    branches:
      - master
      - develop
      - qa

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create alpha Release
        if: github.ref == 'refs/heads/develop'
        id: create_alpha_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-alpha
          release_name: Release ${{ steps.package-version.outputs.current-version}}-alpha
          target_commitish: 'develop'
          draft: false
          prerelease: false
      - name: Create beta Release
        if: github.ref == 'refs/heads/qa'
        id: create_beta_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-beta
          release_name: Release ${{ steps.package-version.outputs.current-version}}-beta
          target_commitish: 'qa'
          draft: false
          prerelease: false
      - name: Create prod Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: Release ${{ steps.package-version.outputs.current-version}}
          target_commitish: 'master'
          draft: false
          prerelease: false