on:
  push:
    branches:
      - master
      - develop
      - qa

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 0 ${{ github.event.after }})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create alpha Release
        if: github.ref == 'refs/heads/develop'
        id: create_alpha_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-alpha
          release_name: V${{ steps.package-version.outputs.current-version}}-alpha
          body: ${{ COMMIT_MESSAGE }}
          draft: false
          prerelease: false
      - name: Create beta Release
        if: github.ref == 'refs/heads/qa'
        id: create_beta_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-beta
          release_name: V${{ steps.package-version.outputs.current-version}}-beta
          body: ${{ COMMIT_MESSAGE }}
          draft: false
          prerelease: false
      - name: Create prod Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: V${{ steps.package-version.outputs.current-version}}
          body: ${{ COMMIT_MESSAGE }}
          draft: false
          prerelease: false
