on:
  push:
    branches:
      - master
      - develop
      - qa

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Develop Changelog
        if: github.ref == 'refs/heads/develop'
        uses: scottbrenner/generate-changelog-action@master
        id: DevelopChangelog
        env:
          REPO: ${{ github.repository }}
      - name: QA Changelog
        if: github.ref == 'refs/heads/qa'
        uses: scottbrenner/generate-changelog-action@master
        id: QAChangelog
        env:
          REPO: ${{ github.repository }}
      - name: Changelog
        if: github.ref == 'refs/heads/master'
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create alpha Release
        if: github.ref == 'refs/heads/develop'
        id: create_alpha_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-alpha
          release_name: Release ${{ steps.package-version.outputs.current-version}}-alpha
          body: |
            ${{ steps.DevelopChangelog.outputs.changelog }}
          target_commitish: 'develop'
          draft: false
          prerelease: false
      - name: Create beta Release
        if: github.ref == 'refs/heads/qa'
        id: create_beta_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}-beta
          release_name: Release ${{ steps.package-version.outputs.current-version}}-beta
          body: |
            ${{ steps.QAChangelog.outputs.changelog }}
          target_commitish: 'qa'
          draft: false
          prerelease: false
      - name: Create prod Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: Release ${{ steps.package-version.outputs.current-version}}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          target_commitish: 'master'
          draft: false
          prerelease: false